version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfiles/frontend.dockerfile
    container_name: frontend_container
    ports:
      - "80:80"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - monitoring
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
    external: true
