jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Debug Information
        run: |
          ls -l
          echo "Current Directory: $PWD"
          echo "Contents of src/components/layout: $(ls -l src/components/layout)"
